"""Public API for the Phase3 strict web-knowledge contracts."""

from .contracts import (
    INTERNAL_INFERENCE_SOURCE_NAME,
    SCHEMA_VERSION,
    UNKNOWN_PATCH,
    Claim,
    ClaimType,
    ContractBundle,
    ContractError,
    FusionStatus,
    KnowledgeRecord,
    QueryResult,
    SourceRecord,
    SourceType,
    strict_json_load,
    strict_json_loads,
    validate_bundle,
    validate_claim,
    validate_contract_bundle,
    validate_knowledge_record,
    validate_query_result,
    validate_source_record,
)

__all__ = [
    "SCHEMA_VERSION",
    "UNKNOWN_PATCH",
    "INTERNAL_INFERENCE_SOURCE_NAME",
    "ContractError",
    "SourceType",
    "ClaimType",
    "FusionStatus",
    "SourceRecord",
    "Claim",
    "KnowledgeRecord",
    "QueryResult",
    "ContractBundle",
    "strict_json_loads",
    "strict_json_load",
    "validate_source_record",
    "validate_claim",
    "validate_knowledge_record",
    "validate_query_result",
    "validate_contract_bundle",
    "validate_bundle",
]
